# Generated by Django 5.1.6 on 2025-03-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='account',
            name='endereco',
        ),
    ]
